---
title: "Sulfate over time plots"
author: 
Zhang Zhenglin
output:
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: sentence
---

# Necessary libraries

```{r message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(FluxCalR)
library(tidyverse)
library(fuzzyjoin)
library(purrr)
library(data.table)
library(broom)
library(lubridate)
library(readxl)
library(openxlsx)
library(ggrepel)
library(gridExtra)
library(zoo)
```

# Load data

```{r}
flux <- read_excel("../Data/flux_data_RGF_through_2025_07_01.xlsx", sheet = 1)
str(flux)
```

# Allocate plot to treatments

```{r}

flux <- flux %>%
mutate(Treatment = case_when(
  plot_number %in% c("105", "201", "301") ~ "CF",
  plot_number %in% c("106", "206", "302") ~ "CF-PP",
  plot_number %in% c("101", "204", "306") ~ "LD",
  plot_number %in% c("103", "205", "304") ~ "LD-PP",
  plot_number %in% c("102", "203", "305") ~ "LD-MS",
  TRUE ~ "Other" # This line handles cases where plot is not listed
)) %>%
  filter(Treatment != "Other") #%>%
  # filter(Treatment != "LD-MS") %>%
  # filter(Treatment != "CF-PP") 

#change to the right variable classes
flux$plot_number <- as.factor(flux$plot_number)
flux$Treatment <- as.factor(flux$Treatment)

#check that all variables look good
str(flux)
```

# Number of sampling events

```{r}
flux %>%
  summarise(n_dates = n_distinct(date_sampled_AD))
```

# Linear Interpolation

```{r}
flux_2025 <- flux %>%
  filter(date_sampled_AD >= as.POSIXct("2025-05-01") & date_sampled_AD <= as.POSIXct("2025-10-06"))


start_date <- as.Date("2025-05-02")
end_date <- as.Date("2025-07-02")
date_seq <- seq.Date(start_date, end_date, by = "day")

flux_2025_rice_interpolated <- flux_2025 %>%
  group_by(plot_number) %>%
  complete(date_sampled_AD = date_seq) %>%
  ungroup()

flux_2025_rice_interpolated <- flux_2025_rice_interpolated %>%
  group_by(plot_number) %>%
  mutate(CH4_flux_mgm2h = na.approx(CH4_flux_mgm2h, rule = 2)) %>%
  mutate(CH4_flux_g_ha_day = CH4_flux_mgm2h*240 )%>%
  ungroup()

flux_2025_rice_seasonal_emissions <- flux_2025_rice_interpolated %>%
  group_by(plot_number) %>%
  summarize(total_CH4_emissions = sum(CH4_flux_g_ha_day, na.rm = TRUE))%>% 
            #total_N2O_emissions = sum(N2O_g_ha_day, na.rm = TRUE)) 
  mutate(Period_Year = "Summer_2025") %>%
  mutate(Period = "Summer") %>%
  mutate(total_CH4_emissions_kg_ha = total_CH4_emissions/1000)%>%
  mutate(Treatment = case_when(
  plot_number %in% c("105", "201", "301") ~ "CF",
  plot_number %in% c("106", "206", "302") ~ "CF-PP",
  plot_number %in% c("101", "204", "306") ~ "LD",
  plot_number %in% c("103", "205", "304") ~ "LD-PP",
  plot_number %in% c("102", "203", "305") ~ "LD-MS",
  TRUE ~ "Other" # This line handles cases where plot is not listed
)) %>%
  filter(Treatment != "Other") %>%
  mutate(Drain = case_when(
  plot_number %in% c("105", "201", "301") ~ "CF",
  plot_number %in% c("106", "206", "302") ~ "CF",
  plot_number %in% c("101", "204", "306") ~ "LD",
  plot_number %in% c("103", "205", "304") ~ "LD",
  plot_number %in% c("102", "203", "305") ~ "LD",
  TRUE ~ "Other" # This line handles cases where plot is not listed
)) %>%
  mutate(Sulfate = case_when(
  plot_number %in% c("105", "201", "301") ~ "0",
  plot_number %in% c("106", "206", "302") ~ "300",
  plot_number %in% c("101", "204", "306") ~ "0",
  plot_number %in% c("103", "205", "304") ~ "300",
  plot_number %in% c("102", "203", "305") ~ "350",
  TRUE ~ "Other" # This line handles cases where plot is not listed
)) 


flux_2025_rice_seasonal_emissions$Drain <- as.factor(flux_2025_rice_seasonal_emissions$Drain)
flux_2025_rice_seasonal_emissions$Sulfate <- as.factor(flux_2025_rice_seasonal_emissions$Sulfate)
flux_2025_rice_seasonal_emissions$Treatment <- as.factor(flux_2025_rice_seasonal_emissions$Treatment)

ggplot(flux_2025_rice_interpolated, aes(y=CH4_flux_g_ha_day, x=date_sampled_AD, color = plot_number)) + geom_point()
#ggplot(flux_2025_rice_interpolated, aes(y=N2O_g_ha_day, x=Date, color = Plot)) + geom_point()
```



# Put dates of agronomic significance into a dataframe

```{r}
events <- data.frame(
  event = c("Planting date", "Initial Flood", "Drain start",
            "Drain reflood", "End-of-season drain", 
            "Harvest date", "Pre-season sulfate", 
            "Mid-season sulfate"),
  date = as.Date(c("2025-05-10", "2025-05-07", "2025-06-21",
                   "2025-07-01", NA, NA, "2025-05-01", 
                   "2025-07-01"))
)

flux_2025
```


# Plot some graphs huehue

```{r}

methane_all_graphing <- flux_2025 %>%
  group_by(Treatment, date_sampled_AD) %>%
  mutate(CH4_flux_mgm2h_se = sd(CH4_flux_mgm2h)/sqrt(3)) %>%
  summarise(CH4_flux_mgm2h = mean(CH4_flux_mgm2h),
  CH4_flux_mgm2h_se = mean(CH4_flux_mgm2h_se))

methane_over_time <- 
  ggplot(methane_all_graphing, aes(x = date_sampled_AD, y = CH4_flux_mgm2h,  colour =  Treatment))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin=CH4_flux_mgm2h-CH4_flux_mgm2h_se, ymax=CH4_flux_mgm2h+CH4_flux_mgm2h_se), size=0.5)+
  ggtitle("Methane over time")+
  scale_x_datetime(name = "",
    limits = as.POSIXct(c("2025-05-01", "2025-07-15")), # Set x-axis limits
    date_labels = "%b %Y",
    date_breaks = "1 month")+
# pre season sulfate    
  geom_vline(xintercept = as.POSIXct(c("2025-05-01")), 
             linetype = "dashed", color = "red") +
  geom_text(aes(x = as.POSIXct("2025-05-01"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Pre-season sulfate"),
            angle = 90, vjust = -0.5, hjust = 0, color = "red", size =4) +

# mid season sulfate    
  geom_vline(xintercept = as.POSIXct(c("2025-07-01")), 
             linetype = "dashed", color = "red") +
  geom_text(aes(x = as.POSIXct("2025-07-01"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Mid-season sulfate"),
            angle = 90, vjust = 1.4, hjust = 0, color = "red", size =4)   +

# Initial Flood    
  geom_vline(xintercept = as.POSIXct(c("2025-05-07")), 
             linetype = "dashed", color = "blue") +
  geom_text(aes(x = as.POSIXct("2025-05-07"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Initial flood"),
            angle = 90, vjust = -0.5, hjust = 0, color = "blue", size =4)    +
  
# Begin mid season drain     
  geom_vline(xintercept = as.POSIXct(c("2025-06-21")), 
             linetype = "dashed", color = "blue") +
  geom_text(aes(x = as.POSIXct("2025-06-21"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Drain start"),
            angle = 90, vjust = -0.5, hjust = 0, color = "blue", size =4) +
  
# Reflood after mid season drain     
  geom_vline(xintercept = as.POSIXct(c("2025-07-01")), 
             linetype = "dashed", color = "blue") +
  geom_text(aes(x = as.POSIXct("2025-07-01"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Drain end"),
            angle = 90, vjust = -0.5, hjust = 0, color = "blue", size =4) +

# Planting date
  geom_vline(xintercept = as.POSIXct(c("2025-05-10")), 
             linetype = "dashed", color = "darkgreen") +
  geom_text(aes(x = as.POSIXct("2025-05-10"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Planting"),
            angle = 90, vjust = -0.5, hjust = 0, color = "darkgreen", size =4)   
  
  
methane_over_time


ggsave(methane_over_time, filename = "../Figures/methane_over_time.jpg", height = 25, width = 30, units = "cm", dpi=400)
```
## Graph with soil sampling dates

```{r}
methane_over_time_soil_dates <- 
  ggplot(methane_all_graphing, aes(x = date_sampled_AD, y = CH4_flux_mgm2h,  colour =  Treatment))+
  geom_point()+
  geom_line()+
  geom_errorbar(aes(ymin=CH4_flux_mgm2h-CH4_flux_mgm2h_se, ymax=CH4_flux_mgm2h+CH4_flux_mgm2h_se), size=0.5)+
  ggtitle("Methane over time")+
  scale_x_datetime(name = "",
    limits = as.POSIXct(c("2025-05-01", "2025-08-30")), # Set x-axis limits
    date_labels = "%b %Y",
    date_breaks = "1 month")+
# pre season sulfate    
  geom_vline(xintercept = as.POSIXct(c("2025-05-01")), 
             linetype = "dashed", color = "red") +
  geom_text(aes(x = as.POSIXct("2025-05-01"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Pre-season sulfate"),
            angle = 90, vjust = -0.5, hjust = 0, color = "red", size =4) +

# mid season sulfate    
  geom_vline(xintercept = as.POSIXct(c("2025-07-01")), 
             linetype = "dashed", color = "red") +
  geom_text(aes(x = as.POSIXct("2025-07-01"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Mid-season sulfate"),
            angle = 90, vjust = 1.4, hjust = 0, color = "red", size =4)   +

# Initial Flood    
  geom_vline(xintercept = as.POSIXct(c("2025-05-07")), 
             linetype = "dashed", color = "blue") +
  geom_text(aes(x = as.POSIXct("2025-05-07"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Initial flood"),
            angle = 90, vjust = -0.5, hjust = 0, color = "blue", size =4)    +
  
# Begin mid season drain     
  geom_vline(xintercept = as.POSIXct(c("2025-06-21")), 
             linetype = "dashed", color = "blue") +
  geom_text(aes(x = as.POSIXct("2025-06-21"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Drain start"),
            angle = 90, vjust = -0.5, hjust = 0, color = "blue", size =4) +
  
# Reflood after mid season drain     
  geom_vline(xintercept = as.POSIXct(c("2025-07-01")), 
             linetype = "dashed", color = "blue") +
  geom_text(aes(x = as.POSIXct("2025-07-01"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Drain end"),
            angle = 90, vjust = -0.5, hjust = 0, color = "blue", size =4) +

# Planting date
  geom_vline(xintercept = as.POSIXct(c("2025-05-10")), 
             linetype = "dashed", color = "darkgreen") +
  geom_text(aes(x = as.POSIXct("2025-05-10"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Planting"),
            angle = 90, vjust = -0.5, hjust = 0, color = "darkgreen", size =4) +

# Soil sampling dates
  geom_vline(xintercept = as.POSIXct(c("2025-06-17")), 
             linetype = "dashed", color = "brown") +
  geom_text(aes(x = as.POSIXct("2025-06-17"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Pre Drain soils"),
            angle = 90, vjust = -0.5, hjust = 0, color = "brown", size =4)   +

  
  # Soil sampling dates
  geom_vline(xintercept = as.POSIXct(c("2025-07-14")), 
             linetype = "dashed", color = "brown") +
  geom_text(aes(x = as.POSIXct("2025-07-14"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Post Reflood soils"),
            angle = 90, vjust = -0.5, hjust = 0, color = "brown", size =4) +
 
   # Soil sampling dates
  geom_vline(xintercept = as.POSIXct(c("2025-08-19")), 
             linetype = "dashed", color = "brown") +
  geom_text(aes(x = as.POSIXct("2025-08-19"), 
                y = mean(CH4_flux_mgm2h, na.rm = TRUE) * 1.05,
                label = "Late soils"),
            angle = 90, vjust = -0.5, hjust = 0, color = "brown", size =4) 
  
methane_over_time_soil_dates

ggsave(methane_over_time_soil_dates, filename = "../Figures/methane_over_time_soil_dates.jpg", height = 25, width = 30, units = "cm", dpi=400)
```



```{r}
model <- lm(total_CH4_emissions_kg_ha~Treatment, data=flux_2025_rice_seasonal_emissions)
anova(model)

Treatment_means = emmeans(model,spec = 'Treatment')
Treatment_effects = contrast(Treatment_means, method = 'pairwise', adjust = "Tukey")
summary(Treatment_effects)
cld(Treatment_means)

ggplot(flux_2025_rice_seasonal_emissions, aes(y=total_CH4_emissions_kg_ha, x=Treatment, color = Treatment)) + geom_boxplot()

```

# Anlyses for sulfate:drain interaction - very important 

```{r}
model <- lm(total_CH4_emissions_kg_ha~Drain*Sulfate, data=flux_2025_rice_seasonal_emissions)
anova(model)

Treatment_means = emmeans(model,spec = 'Drain', by = "Sulfate")
Treatment_effects = contrast(Treatment_means, method = 'pairwise', adjust = "Tukey")
summary(Treatment_effects)
cld(Treatment_means)

# if we look at the summary output, sulfate = 350 has CF as not estimated. This is because the experiment is not a full 2x3 factorial design we probably have to play around with the linear model to account for that. 

ggplot(flux_2025_rice_seasonal_emissions, aes(y=total_CH4_emissions_kg_ha, x=Treatment, color = Treatment)) + geom_boxplot()

```
