---
title: "Yield"
author: "Zhang Zhenglin"
output:
  pdf_document:
    toc: yes
editor_options:
  markdown:
    wrap: sentence
---

# Necessary libraries

```{r message=FALSE,warning=FALSE}
library(knitr)
library(ggplot2)
theme_set(theme_bw())
library(emmeans)
library(multcomp)
library(PLS205)
library(lme4)
library(lmerTest)
library(multcompView)
library(car)
library(Rmisc) 
library(dplyr) #https://r4ds.had.co.nz/ (Chapter 3, Chapter 5, look at filter and select)
# https://bookdown.org/ansellbr/WEHI_tidyR_course_book/
library(stringr) 
library(data.table)
library(GGally)
library(formatR)
library(readxl)
library(FluxCalR)
library(tidyverse)
library(fuzzyjoin)
library(purrr)
library(data.table)
library(broom)
library(lubridate)
library(readxl)
library(openxlsx)
library(ggrepel)
```

# Read data

```{r}
yield <- read_excel("../Data/yield_data.xlsx", sheet = 1) %>%
  mutate(Treatment = case_when(
  Plot %in% c("105", "201", "301") ~ "CF",
  Plot %in% c("106", "206", "302") ~ "CF-S",
  Plot %in% c("101", "204", "306") ~ "MD",
  Plot %in% c("103", "205", "304") ~ "MD-S",
  Plot %in% c("102", "203", "305") ~ "MD-MS",
  TRUE ~ "Other" # This line handles cases where plot is not listed
)) %>%
  filter(Treatment != "Other") %>% filter(Treatment != "MD-MS") %>% 
  #remove short drain (not a treatment for this study), remove double sulfate treatment (not included in analyses)
  mutate(Sulfate = case_when(
  Plot %in% c("105", "201", "301") ~ "0",
  Plot %in% c("106", "206", "302") ~ "300",
  Plot %in% c("101", "204", "306") ~ "0",
  Plot %in% c("103", "205", "304") ~ "300",
)) %>% 
  filter(Treatment != "Other") %>%
  mutate(Drain = case_when(
  Plot %in% c("105", "201", "301") ~ "CF",
  Plot %in% c("106", "206", "302") ~ "CF",
  Plot %in% c("101", "204", "306") ~ "MD",
  Plot %in% c("103", "205", "304") ~ "MD",
)) %>% 
  mutate(across(where(is.character), as.factor))


str(yield)
```

# Compute yield @ 14% moisture


```{r}
# plants were harvested from a large PVC ring with diameter of 76.2 cm
# grains were stripped by hand and dried @ 60 degrees Celsius
# Here we obtain the dry grain weight, correct for moisture content and scale by area to get yield @ Mg/ha @ 14% moisture

# get bag weights 
yield <- yield %>%
mutate(style_bag_weight = case_when(
  paper_bag_style %in% c("2025_HD") ~ 18.885,
  paper_bag_style %in% c("2025_LD") ~ 12) )

yield$total_bag_weight <- yield$style_bag_weight * yield$number_of_paper_bags                                    

yield$grain_dry <- yield$grain_plus_paper_bag_and_rubberband_oven_dry_weight_g-yield$total_bag_weight
yield$grain_yield <- ((yield$grain_dry*(98.1/86))/1000000)/((pi*(76.2/2)*(76.2/2))/100000000)

```
# ANOVA and post-hoc

```{r}
model <- lm(grain_yield~Drain*Sulfate, data = yield)
anova(model)
means <- emmeans(model, ~ Drain + Sulfate)
cld <- cld(emmeans(model, ~ Drain + Sulfate),adjust = "Tukey")

cld

model_trt <- lm(grain_yield~Treatment, data = yield)
anova(model_trt)
means_trt <- emmeans(model_trt,spec = 'Treatment')
cld_trt <- cld(means_trt,adjust = "Tukey")

cld_trt
```

# Brief Visualization

```{r}
ggplot(yield,
       aes(x=Treatment, y=grain_yield))+
  geom_boxplot()+
  geom_point()
```

